fix: pin anthropic version, count_tokens was replaced with $ api (#87)
`AttributeError: 'Anthropic' object has no attribute 'count_tokens'`
was caused by anthropic removing this method
https://github.com/anthropics/anthropic-sdk-python/releases/tag/v0.39.0